### PR TITLE
Bugfix: Prevent sending daily digest email if no new Developer signed up yesterday

### LINKED ISSUE #266: An email notification is sent even if no new developer profiles were added
**Describe the bug**
I received an email notification saying "0 new developer profiles were added" this morning.

**To Reproduce**
1. Ensure no developers were added "yesterday"
1. Trigger the daily email notification script

**Expected behavior**
No one should receive an email.

**Actual behavior**
Everyone receives an email stating "0 new developer profiles added to railsdevs".

**Screenshots**
image

### PR DESCRIPTION
**Pull request by salochara**
Fixes #266 
-> Prevent sending daily digest email if no new dev signed up the day before

### Pull request checklist

- [X] Your code contains tests relevant for code you modified
- [X] You have linted and tested the project with `bin/check`

### CODE REVIEW

File: test/models/email_digests/new_developers_test.rb [hunk 1]
```diff
@@ -10,6 +10,14 @@ class EmailDigests::NewDevelopersTest < ActionMailer::TestCase
...
   end
 
+  test "do not send daily emails if no new developers signed up yesterday" do
+    create_developer(2.days.ago)
+
+    assert_no_emails do
+      EmailDigests::NewDevelopers.new.send_daily_digest
+    end
+  end
+
```
Comment (joemasilotti) [inline test/models/email_digests/new_developers_test.rb:20]: Can this be done with the current seeds by time traveling to a specific date? Then we wouldn't have to manually create any developers or pull out the params from the other test.

**Review by joemasilotti — CHANGES_REQUESTED** [review]

File: test/models/email_digests/new_developers_test.rb (hunk 1 above)
Comment (salochara) [reply test/models/email_digests/new_developers_test.rb]: Done! 
What do you think?

**Comment by joemasilotti** [comment]
Thanks again for the contribution! I did a little house keeping and we are now good to merge.
