### PR TITLE
Bugfix #229: Show Add/Update my profile based on user status

### LINKED ISSUE #229: In /developers add my profile button shows when user is logged in
**Describe the bug**
I don't know to actually classify this as a bug, because maybe it's intended. 

I find it weird that something that invites you to create a profile shows up when you already have one.

Maybe add a button to your existing profile or it could be used in the future to tell the developer/business that they need to update it in the case new required fields are added.

**To Reproduce**
1. Sign in as a business or developer
2. Go to `/developers`
3. See `add my profile` button

**Screenshots**
Screen Shot 2022-01-09 at 20 43 24

### PR DESCRIPTION
**Pull request by dhairyagabha**
Fixes #229 

### Pull request checklist

- [x] Your code contains tests relevant for code you modified
- [x] You have linted and tested the project with `bin/check`

Screen Shot 2022-02-26 at 11 38 58 AM

### CODE REVIEW

File: app/components/developer_profile_create_component.rb [hunk 1]
```diff
@@ -0,0 +1,7 @@
+# frozen_string_literal: true
```
Comment (joemasilotti) [inline app/components/developer_profile_create_component.rb:1]: Please remove this comment.

File: app/components/developer_profile_create_component.rb [hunk 2]
```diff
@@ -0,0 +1,7 @@
...
+
+class DeveloperProfileCreateComponent < ApplicationComponent
+  def initialize(user)
+    @user = user
```
Comment (joemasilotti) [inline app/components/developer_profile_create_component.rb:5]: Please add a read only property instead of referencing the ivar in the view. `attr_reader :user`

File: app/components/developer_profile_create_component.rb [hunk 3]
```diff
@@ -0,0 +1,7 @@
+# frozen_string_literal: true
+
+class DeveloperProfileCreateComponent < ApplicationComponent
```
Comment (joemasilotti) [inline app/components/developer_profile_create_component.rb:3]: I think `DeveloperProfileActionComponent` makes more sense.

**Review by joemasilotti — CHANGES_REQUESTED** [review]
Looks great! I made a few tiny change requests.

File: app/components/developer_profile_action_component.html.erb [hunk 4]
```diff
@@ -0,0 +1,13 @@
+<div class="mt-4 flex space-x-3 md:mt-0">
+  <% if user&.developer %>
```
Comment (joemasilotti) [inline app/components/developer_profile_action_component.html.erb:2]: Ok, last change (I missed this last time, sorry). Can this be moved to the component and not the view? `add?` or `new?` method on the component could work.

**Review by joemasilotti — CHANGES_REQUESTED** [review]

**Comment by dhairyagabha** [comment]
@joemasilotti  Done.

I agree with it. Should have thought of it.

**Review by joemasilotti — APPROVED** [review]

**Comment by joemasilotti** [comment]
Thanks! Approved - I'll merge this in tonight.
